### ISSUE TITLE
Merge [more frequent] expansions using FIFO, not LIFO

### ISSUE THREAD

**Issue by radiovisual** [npm/npm-expansions#1103]
I have submitted [100+ expansions](https://github.com/npm/npm-expansions/pulls/radiovisual), but only 2 of them have been merged. I noticed that only a few contributed expansions get merged each month, and you use a LIFO (Last In, First Out) system, which means the people who contributed first are being overlooked by the newest contributions. 

For example, I have one expansion: [`Narnia's Psychedelic Mushrooms`](https://github.com/npm/npm-expansions/pull/1061) that I submitted 29 days ago, but just the other day you merged a similar expansion: [`Neolithic Psychedelic Mushrooms`](https://github.com/npm/npm-expansions/commit/f37d5640378017bb3f2a8e87f80d47c0600284fa) that was submitted 4 days ago, so naturally I feel like mine won't be merged now, because it is now too similar to an existing expansion, even though mine was submitted 25 days earlier. So a FIFO (First In, First Out) system keeps everything balanced, and fair.

It is really fun to participate in this expansions repo, and see our contributions on the npm site, which we use everyday, but lately our contributions aren't really being added (only a couple each month). So I propose that you merge your pull requests using a First In, First Out system, so the earliest contributors get proper credit, and aren't lost to oblivion.

Lastly, if you need some help, I am happy to help you do the grunt work. Even with 100+ contributions, I am still yet to see any of my expansions on the npm website, and it is, after all, a dream of mine to see my contribution shining in the top-left corner of the npm website I use everyday. :smiley: :heart:

**Comment by rozzzly** [comment]
**Alternate Solution:** Once a month (or every other week, etc) aggregate all new submission. Hold a vote for the top X number of them. Winners get merged; perhaps all at once, or gradually. This could be on the npm website, or over twitter w/ a `#hashtag`. The latter is free PR & boosts community engagement :wink: 


#NewProgenitorsMonthy ? --- as you can tell, I'm not very good at this, but I'd sure like to help select those that are!

**Comment by seldo** [comment]
What actually happened: I was being CEO for 3 months while Isaac was on paternity leave, so I just ignored this entirely. Back to normal schedule now.
