### ISSUE TITLE
Is anyone actually looking at the pull requests?

### ISSUE THREAD

**Issue by Gum-Joe** [npm/npm-expansions#1121]
I don't mean to be rude, but I looked at the amount of pull requests open, and there is quite a lot!
I kindly respect the fact it takes time to look through, as of writing, 238 pull requests, although I would be happy to, at some point, look though some of the pull requests.

**Comment by Gum-Joe** [comment]
Turns out someone is looking at these, just it probably takes time.

**Comment by MiLeung** [comment]
That someone isn't looking frequently enough!
