### ISSUE TITLE
When the expansions link on the site is clicked it becomes blue underlined until something else is clicked on

### ISSUE THREAD

**Issue by GusCaplan** [npm/npm-expansions#1136]
When the expansions link on the site is clicked it becomes blue underlined until something else is clicked on. (until unselected)
![image](http://static.fluffycraft.net/images/npmissue.png)
Just so you guys know.

**Comment by The-Technicalist** [comment]
This is a result of the page's css, not relative to this extension.
If they wanted to fix it they could just add some random class with `npm-expansions` such as `no-underline` and right under it put
<style> .no-underline a:visited { text-decoration: none } </style>` but i don't think they care  :P

**Comment by GusCaplan** [comment]
i know that i just thought this would be a good place to let them know

**Comment by bjskistad** [comment]
It doesn't do that for me, at least, not anymore.

**Comment by GusCaplan** [comment]
@bjskistad maybe they saw this and fixed it 😄

**Comment by GusCaplan** [comment]
wait nvm still happening

**Comment by bjskistad** [comment]
@GusCaplan What's your OS and what browser are you using?

**Comment by GusCaplan** [comment]
@bjskistad windows chrome and osx chrome

**Comment by bjskistad** [comment]
Hmmm... I'm on a chromebook. (With chrome for browser of course)

**Comment by seldo** [comment]
Submit this as an issue to npm/newwww instead :-)
