### ISSUE TITLE
Expand it to cyrillic soviet Russia?

### ISSUE THREAD

**Issue by sudodoki** [npm/npm-expansions#156]
Just a random "И0ДЕ РАСКАGЕ МАНАGЕЯ" proposal. Yay/nay?

**Comment by Ekunia** [comment]
100% agree. But...wouldn't it be "ИOДЕ РАСКАGЕ МАЙАGЕЯ", not "Eodye Paskagye Managyeya"? I'm assuming you just mean faux-Cyrillic and not the proper translit.

**Comment by vitaly-t** [comment]
Why generate random nonsense when it can be something meaningful?

P.S. I am a Russian speaker.

**Comment by Ekunia** [comment]
Because it amuses Americans, who guess that it means what it appears to be in English -- for instance I believe "Д" is actually "A" in faux-Cyrillic.

**Comment by vitaly-t** [comment]
Ignorance is bliss, and it is not so amusing to those who speak the language, it just looks dumb.
