### ISSUE TITLE
#15 'Nagging Mario's Princess' abbreviates to nmp not npm

### ISSUE THREAD

**Issue by webwaffle** [npm/npm-expansions#2100]

**Comment by timmyrs** [comment]
They should've required does-acronym-match because being competent without dependencies is clearly not something they're capable of.

**Comment by timmyrs** [comment]
They deleted my comment about how nodejs developers are idiots but didn't fix the bug :thinking:

**Comment by rocketicv** [comment]
@timmyrs, they have fixed the bug now. I do not see why calling loads of devs who created software you use, "idiots", was helpful or necessary.

**Comment by timmyrs** [comment]
I don't use npm or nodejs, I just regularly check out what the people who need a library for literally every single task are up to.

**Comment by rocketicv** [comment]
@timmyrs OK buddy, go be a 10xer somewhere else.

**Comment by timmyrs** [comment]
I didn't even know 10xer was a term until now. I guess I'm honoured you're calling me ten times better, lol.

**Comment by rocketicv** [comment]
Yes, it's geniuses like you who uphold society. Now go rewrite something in Rust.

**Comment by timmyrs** [comment]
You can't tell me what to do. I'd much rather make a library for checking of something is precisely equal to false, and I'll call it ThreeEqualSignsAsALibrary.js
