### ISSUE TITLE
Following Regex useful for checking the NPM-ness of an entry

### ISSUE THREAD

**Issue by computamike** [npm/npm-expansions#2254]
`const regex = /^[nN]\S+ [pP]\S+ [mM]\S+$/msg;
`

**Comment by jedwards1211** [comment]
i flag, dude

**Comment by ArthurKa** [comment]
Almost year past) Still no reaction))

**Comment by darcyclarke** [comment]
@computamike we've got a backlogged item to clean up this repo with some automation that should help with that type of check/verification. Appreciate the contribution! You can check out the work [here](https://github.com/npm/npm-expansions/tree/feature/automation-refactor).
