### ISSUE TITLE
Needs more pumpkin

### ISSUE THREAD

**Issue by missmatsuko** [npm/npm-expansions#2257]
I see ~10 pumpkin-themed 'npm texts' on the live site, and wanted to add more, but noticed that `expansions.txt` only has 3 pumpkin texts. Where are the other pumpkins coming from?

**Comment by jedwards1211** [comment]
next pumpkin, ma'am

**Comment by patrickhrastnik** [comment]
Nice Pumpkin Manager

**Comment by mikemimik** [comment]
Hello @missmatsuko love "needs more pumpkin"! Though it doesn't quite conform to the initials NPM.

Alternate Suggestions:
- Need Pumpkin Meow
- Nice Pumpkin Manager (from @patrickhrastnik)
- Next Pumpkin, Ma'am (from @jedwards1211)

Once you've come up with a phrase, please create a pull-request for it :D

Looking forward to seeing it, and I'm going to close this issue for now :]

**Comment by missmatsuko** [comment]
I never got my question answered, though. On pumpkin day, I saw more pumpkin-related messages than actually existed in `expansions.txt`, so I wouldn't know where to PR it.

**Comment by mikemimik** [comment]
Oh I'm terribly sorry @missmatsuko! I'm not sure why you were able to see more on the website. I also only see three pumpkin related items in the text file. I wasn't with the company then so I don't have any historical context. There might have been a different version of the file used as an easter egg that day.

You can create a pull-request against this repository with your pumpkin related items, and if we do something special in the future, we'll definitely keep you in mind for more ideas!!
