### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by karthick-manoharan** [npm/npm-expansions#2262]
On executing the command `npm test`. I get the following error

```
> npm-expansions@2.2.4 pretest /Users/karthicksubramanianm/codei/npm-expansions
> node build.js


> npm-expansions@2.2.4 test /Users/karthicksubramanianm/codei/npm-expansions
> tap test

sh: tap: command not found
npm ERR! Test failed.  See above for more details.
```

System Information:
--------------------
OS: Mac High Sierra
node: 10.8.0
npm: 6.2.0

**Comment by nicholasfagan** [comment]
I also had this issue.
It is because the tap module is not installed.
Kinda fixed with 'npm install tap', although this made unwanted changes
to package-lock.json which I reverted before committing. 
Not sure why it is not properly working right away though . . .

**Comment by mikemimik** [comment]
Current HEAD of master has a devDependency with `tap` installed. Thanks for the issue! This should be fixed now!
