### ISSUE TITLE
tap keeps failing

### ISSUE THREAD

**Issue by ryan20090101** [npm/npm-expansions#2322]
**I am opening this issue because:**

- [ ] npm is crashing
- [ ] npm is producing a incorrect install
- [ ] npm is doing something I don't understand
- [x] Other (*see below for feature requests*)

**What's going wrong?**

This issue has been happening since `2.2.4` I was doing `npm test` on npm expansions and it keeps failing.
Here is my complete log about the test
```
> npm-expansions@2.2.4 pretest C:\Users\Jerome\node_modules\npm-expansions
> node build.js


> npm-expansions@2.2.4 test C:\Users\Jerome\node_modules\npm-expansions
> tap test

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'tap'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\Jerome\node_modules\npm-expansions\test\index.js:2:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
test/index.js ......................................... 0/1
  not ok test/index.js
    timeout: 30000
    file: test/index.js
    command: 'C:\Program Files\nodejs\node.exe'
    args:
      - test/index.js
    stdio:
      - 0
      - pipe
      - 2
    cwd: 'C:\Users\Jerome\node_modules\npm-expansions'
    exitCode: 1

total ................................................. 0/1


  0 passing (161.476ms)
  1 failing

npm ERR! Test failed.  See above for more details.
```

**How to reproduce the problem**

Install `tap` and `npm-expansions` then
```
cd node_modules
cd npm-expansions
npm test
```

### Supporting information

-   `npm config get registry` prints `https://registry.npmjs.org`
-  `npm -v` prints `6.4.1`
-  `node -v` prints `v10,11,0`
-  OS: Windows
-  Network issues: None
-  Location where npm was run: US
    - [ ] I use a proxy to connect to the npm registry
    - [ ] I use a proxy to connect to the web
    - [ ] I use a proxy when downloading a Git repos
    - [ ] I access the npm registry via a VPN
    - [ ] I don't use a proxy, but have limited or unreliable internet acess
- Container:
    - [ ] I develop using Vagrant on Windows
    - [ ] I develop using Vagrant on OS X or Linux
    - [ ] I develop / deploy using Docker
    - [ ] I develop to a PaaS (Triton, Heroku)

**Comment by mikemimik** [comment]
Re: https://github.com/npm/npm-expansions/issues/2262#issuecomment-533959224

This should be all fixed up now!
