### ISSUE TITLE
not able to install ngeohash 

### ISSUE THREAD

**Issue by blyadav511** [npm/npm-expansions#2331]
I have npm installed in my machine. But not able to install module ngeohash via npm. Please find the error message below. Any help will be appreciated.
npm -v
6.5.0

npm install ngeohash
> ngeohash@0.6.1 install /Users/babu.yadav/repo/devices_api_node/node_modules/ngeohash
> browserify . -o ngeohash.js -s ngeohash

sh: browserify: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ngeohash@0.6.1 install: `browserify . -o ngeohash.js -s ngeohash`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the ngeohash@0.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/babu.yadav/.npm/_logs/2018-12-16T09_35_23_786Z-debug.log

**Comment by jackall3n** [comment]
I'm not sure npm-expansions can help with this issue, try the [npm](https://github.com/npm/npm) project, or even [ngeohash](https://github.com/sunng87/node-geohash) itself
