### ISSUE TITLE
npm pacakge install fails continuously

### ISSUE THREAD

**Issue by ThiyagarajanManivannan** [npm/npm-expansions#2336]
This is the error I am getting when i try to build the package.
Fetching packages...
{ Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:371:17) errno: -5, code: 'Z_BUF_ERROR' }

node --version
v6.15.1

**Comment by mikemimik** [comment]
Hello @ThiyagarajanManivannan if you pull the latest from `master` are you still seeing this error?

**Comment by darcyclarke** [comment]
Can't seem to reproduce this error so I'm going to close this issue. @ThiyagarajanManivannan Definitely feel free to reopen if there's any specific steps we can follow to replicate the issue. Thanks!
