### ISSUE TITLE
Maintenance status of this repo? Thinking using a bot could be helpful.

### ISSUE THREAD

**Issue by andersonaddo** [npm/npm-expansions#2394]
@seldo @zeke 
Basically echoing #1632
It looks like this repo has been pretty inactive since mid 2018, I'm just wondering if it's still being maintained?
Otherwise it probably shouldn't be linked to https://www.npmjs.com/. Maybe, you can use a bot to maintain this repo instead? I don't imagine that being exceptionally difficult, and would make this repo a lot more useful. I could implement one, if you guys want.

**Comment by zeke** [comment]
I no longer have admin access to this repo.

**Comment by andersonaddo** [comment]
@zeke Do you happen to know how is the admin?

**Comment by zeke** [comment]
@seldo was the de facto maintainer for a long time, but I think they no longer pay attention to this repo. Even if this project was still actively maintained, I don't think your proposal to use a bot would work, as it really takes a human to know whether a given expansion is "good" or not.

**Comment by nuflowx** [comment]
although looking through all those pull requests I'd lose interest myself xD
And to be fair, the list (`expansions.txt`) is fairly long already.

But agreed, maybe get the the link removed from npm and/or mention this is no longer an active repo. Or of course find somebody else to take interest in maintaining this. (I don't believe a bot would work out though :P)

**Comment by SidneyNemzer** [comment]
A bot could at least check that expressions are valid, eg, initials are "NPM" and they don't start with [the banned words](https://github.com/npm/npm-expansions#no-more-please).

**Comment by KennethSweezy** [comment]
Going along with the bot solution idea, it could require that it have a certain amount of +1's before it gets merged. This would be a simple way of telling if the community thinks that it is "good" or not.

**Comment by jackall3n** [comment]
Although having bot would be a cool thing, given how easy it could be to get something offensive or embarrassing onto the live site will probably stop it from ever happening.

Having said that, the implementation of a bot that filters out expansions that are "_gendered, sexual, aggressive, or violent_" and adhere to npm's [code of conduct](https://www.npmjs.com/policies/conduct/) would be really interesting to see.

**Comment by danbulant** [comment]
The bot could be just to filter out PRs, the remainings would still need to pass verification by human.

**Comment by darcyclarke** [comment]
@andersonaddo thanks for the ping. We're looking to clean up this repo/project with some work that's being done in [this branch](https://github.com/npm/npm-expansions/tree/feature/automation-refactor). We'll hopefully be able to automate a lot of the checks/verification so that more folks can contribute.

We love the entries the community have given us over the years and hope we can support even more going forward. Keep an eye out for some updates in the near future.
