### ISSUE TITLE
I updated to version 10. Still same error

### ISSUE THREAD

**Issue by APinfinity** [npm/npm-expansions#2500]
I updated to version 10. Still same error 

$ npm install webdriverio
npm ERR! code E405
npm ERR! 405 Method Not Allowed: webdriverio@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\nc442q\AppData\Roaming\npm-cache\_logs\2018-07-11T16_24_06_440Z-debug.log

_Originally posted by @chandnarendra2409 in https://github.com/npm/npm/issues/21184#issuecomment-404230485_

**Comment by jackall3n** [comment]
Seems like the wrong repo my man

**Comment by mikemimik** [comment]
@APinfinity I think you've created an issue on the wrong repository! 👀 
If the above is still a valid concern, might I suggest you head to `https://npm.community` :D
