### ISSUE TITLE
Duplicate expansions.txt entry

### ISSUE THREAD

**Issue by alt-jero** [npm/npm-expansions#2616]
"Norse Power Metal" is doubled.
This might be intentional... If so:
"Nope! Preciously Meticulous."

**Comment by ArthurKa** [comment]
"Noodles, Poodles and More!" also has a duplicate.

**Comment by darcyclarke** [comment]
@alt-jero @artburkart we've got a backlogged item to clean up the repo & add some automation. We'll dedupe an entries at that time as well. Thanks for flagging this though!
