### ISSUE TITLE
text in the mirrored font at 791 and 792

### ISSUE THREAD

**Issue by kewalpasad** [npm/npm-expansions#2718]
Line number 791 and 792 are mirrored not sure if it was meant to be that way or a mistake just wanted to give a heads up. Also it might look weird on npm website.

nuǝɯ pǝɥsᴉꞁod mǝu
nuǝW pǝuoᴉʇᴉsoԀ ʎlǝʌᴉʇɐƃǝN

**Comment by jowsey** [comment]
I'm sure they're intentional. Upside-down text isn't a bug, they're entirely unique unicode characters - if they're there, someone intentionally added those characters to the file. Presumably as a nod to "negatively positioned".. or "pǝuoᴉʇᴉsoԀ ʎlǝʌᴉʇɐƃǝN".
