### ISSUE TITLE
BROKEN JSON

### ISSUE THREAD

**Issue by goblortikus** [npm/npm-expansions#282]
the no pants mom one in the middle has no comma after it

**Comment by goblortikus** [comment]
I fix it here
https://github.com/npm/npm-expansions/pull/281

**Comment by octalmage** [comment]
dammit @poteto!

**Comment by poteto** [comment]
haha oops, my bad! just noticed another missing comma on https://github.com/npm/npm-expansions/blob/master/index.json#L62 too

**Comment by octalmage** [comment]
:stuck_out_tongue:
