### ISSUE TITLE
[QUESTION] why does the word "naM ,sevitcepsreP weN" is accepted as the meaning of n-p-m

### ISSUE THREAD

**Issue by lat94** [npm/npm-expansions#2898]
# What / Why

> why does the word "naM ,sevitcepsreP weN" is accepted as the meaning of n-p-m in the expansions [file](https://github.com/npm/npm-expansions/blob/master/expansions.txt)?

**Comment by lat94** [comment]
I didn't know the word could be wrote backwards.

**Comment by areeq0325** [comment]
It reads "New Perspectives, Man" backwards.
