### ISSUE TITLE
npm install throwing below error

### ISSUE THREAD

**Issue by Jitesh-Tripathi** [npm/npm-expansions#3073]
# What / Why

> npm install throwing below error
npm ERR! cb.apply is not a function
npm ERR! A complete log of this run can be found in:

node -v :   v14.5.0
npm -v :    6.9.0
OS:  Windows 10

## When

* whenever i did npm install globally or locally is throwing error
log
0 info it worked if it ends with ok
1 warn npm npm does not support Node.js v14.5.0
2 warn npm You should probably upgrade to a newer version of node as we
3 warn npm can't make any promises that npm will work with this version.
4 warn npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
5 warn npm You can find the latest version at https://nodejs.org/
6 verbose cli [
6 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
6 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
6 verbose cli   'install'
6 verbose cli ]
7 info using npm@6.9.0
8 info using node@v14.5.0
9 verbose npm-session 76438a2a5cd04b48
10 silly install runPreinstallTopLevelLifecycles
11 silly preinstall micro-ui@0.1.0
12 info lifecycle micro-ui@0.1.0~preinstall: micro-ui@0.1.0
13 silly install loadCurrentTree
14 silly install readLocalPackageData
15 verbose stack TypeError: cb.apply is not a function
15 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:285:20
15 verbose stack     at FSReqCallback.oncomplete (fs.js:177:5)
16 verbose cwd D:\Project\micro-ui
17 verbose Windows_NT 10.0.17134
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
19 verbose node v14.5.0
20 verbose npm  v6.9.0
21 error cb.apply is not a function
22 verbose exit [ 1, true ]

**Comment by radiovisual** [comment]
It works for me when I test using the same version of node:

![image](https://user-images.githubusercontent.com/5614571/89530922-a2667280-d7ef-11ea-843e-f11b2f297bc9.png)

If you have cloned the repo and you forgot to run the `build` command then you would be [missing the expansions.json file, which is not under version control in the repo](https://github.com/npm/npm-expansions/blob/master/package.json#L21), but only shows up in the final build seen by npm.

**Comment by darcyclarke** [comment]
Closing: Please file an issue against the [npm/cli](https://github.com/npm/cli/issues/new/choose) repo for any `npm` **CLI** bugs or contact support by filing a ticket at https://npmjs.com/support for any website or registry issues.
