### ISSUE TITLE
REACT - not working npm while installing it

### ISSUE THREAD

**Issue by Divij-hub** [npm/npm-expansions#3112]
Did all the command on command line from installing the npm globally npm install -g create-react-app  along with following codes:

npx create-react-app <myprojectname> and also cleared the npm cache but it always get stuck on the line in the image showing the following error. Along with the error:

┌──────────────────────────────────────────────────────────────────┐
│                     npm update check failed                      │
│               Try running with sudo or get access                │
│               to the local update config store via               │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\Smart Sites\.config │
└──────────────────────────────────────────────────────────────────
along with 65 packages are looking for funding [1]: https://i.stack.imgur.com/KJVVp.png

**Comment by Spetsnaz-Dev** [comment]
> Did all the command on command line from installing the npm globally npm install -g create-react-app along with following codes:
> 
> npx create-react-app and also cleared the npm cache but it always get stuck on the line in the image showing the following error. Along with the error:
> 
> ┌──────────────────────────────────────────────────────────────────┐
> │ npm update check failed │
> │ Try running with sudo or get access │
> │ to the local update config store via │
> │ sudo chown -R $USER:$(id -gn $USER) C:\Users\Smart Sites.config │
> └──────────────────────────────────────────────────────────────────
> along with 65 packages are looking for funding [1]: https://i.stack.imgur.com/KJVVp.png

You can remove the config file using `rm -rf .config/configstore` or just locate and delete it.
Alternately, If you don't want to chown your entire .config directory (which contains configuration files from other programs), try:
`sudo chown -R $USER:$(id -gn $USER) "/home/skaestle/.config/configstore/"`

CREDITS : https://stackoverflow.com/questions/45650300/npm-update-check-failed

**Comment by darcyclarke** [comment]
Closing: Please file an issue against the [npm/cli](https://github.com/npm/cli/issues/new/choose) repo for any `npm` **CLI** bugs or contact support by filing a ticket at https://npmjs.com/support for any website or registry issues.
