### ISSUE TITLE
[BUG] <title>

### ISSUE THREAD

**Issue by gildas167** [npm/npm-expansions#3290]
<pre><font color="#4E9A06"><b>gildas167@ubuntu</b></font>:<font color="#3465A4"><b>~</b></font>$ sudo npm install -g @angular/cli
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">code</font> FETCH_ERROR
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> <font color="#75507B">errno</font> FETCH_ERROR
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> invalid json response body at https://registry.npmjs.org/debug reason: Unexpected end of JSON input

<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span> A complete log of this run can be found in:
<span style="background-color:#2E3436"><font color="#D3D7CF">npm</font></span> <span style="background-color:#2E3436"><font color="#CC0000">ERR!</font></span>     /root/.npm/_logs/2021-02-05T02_52_58_465Z-debug.log
</pre>

**Comment by v007rj** [comment]
First try to check the following:-
1)Type the command in your cmd/terminal -       ping registry.npmjs.org
2) From this you will get your IP address.
3) Type this: here( ##.##.##.##) is your IP address.

sudo vi /etc/hosts
##.##.##.## registry.npmjs.org  

4) At last
npm install -g @angular/cli
