### ISSUE TITLE
[FEATURE] Add better testing (using a neural network)

### ISSUE THREAD

**Issue by joeymalvinni** [npm/npm-expansions#3295]
# What / Why
I think the best way to automate the tests that are ran before you can submit a PR is to use train a neural network to classify whether an acronym is good or not. Example repository (full working example): [npm-generator](https://github.com/joeymalvinni/npm-generator/tree/v1.0.0)

## When
* n/a

## Where
* npm-extensions

## How
* Checking whether the acronym is good.

### Current Behavior
* Nothing is checked (I think?)

### Expected Behavior
* Checking whether the acronym is good or not

## Who
* n/a

## References
* n/a

**Comment by bad-lang** [comment]
This sounds pretty interesting. I think you should make it a Node module, and PR an example to show what you're talking about (I had trouble understanding what the point of it is). However, I will check out the repo, it looks cool.

**Comment by nopeless** [comment]
#3950 Implements better test
