### ISSUE TITLE
[QUESTION] Isn't this list updating ?

### ISSUE THREAD

**Issue by Posandu** [npm/npm-expansions#3576]
# What / Why
Isn't this list updating? Last commit was https://github.com/npm/npm-expansions/commit/a12ad3f841270bfd57f31f4c752bca364a30b60d 1.5k PR open

## Where
This Repo

## Who
* n/a

## References
https://github.com/npm/npm-expansions/

**Comment by fucksophie** [comment]
Unmaintaned, it seems.
