### ISSUE TITLE
Several expansions violate instructions in README.md

### ISSUE THREAD

**Issue by owenscott** [npm/npm-expansions#776]
The README instructions suggest to "Avoid expansions that are gendered, sexual, aggressive, or violent. We are a diverse, positive place." This is really awesome and totally expected w/ NPM. However, quite a few of the expansions violate this, e.g. from the README file itself:

    Nymphets Playing Mahjong

Where [Wikipedia](https://en.wikipedia.org/wiki/Lolita_(term)#Nymphet) defines a "*Nymphet*" as "*a sexually attractive girl, or young woman*". Suggest cleaning up some of the more questionable expansions to make the list more in line with the instructions and Code of Conduct.

**Comment by seldo** [comment]
That's a fair criticism! Lots of the expansions were added in a rush in the early days before we decided we needed a policy, and we've cleaned out a bunch. I'll remove this one. If you spot any more, feel free to submit a PR removing them.

**Comment by radiovisual** [comment]
A recent expansion that was merged: `No Pants Mafia` also violates the terms in the "No More Please" section of the README file, since it begins with the word "No"
