### ISSUE TITLE
Is expansions list up-to-date at npmjs.com?

### ISSUE THREAD

**Issue by gregdeane** [npm/npm-expansions#881]
It doesn't seem like many of the recent expansions are live at npmjs.com. Not sure if this is purposeful, a caching issue, or I'm just being dumb.

On the live site, this file appears to contain the expansions: https://www.npmjs.com/static/js/index.min.6833b586.js.

However, those expansions do not match the latest expansions.txt file.

**Comment by jbruni** [comment]
I don't know and I'm not sure, but I guess the live site has latest version, which is 2.2.3: https://github.com/npm/npm-expansions/tree/v2.2.3

I think these latest/most-recent additions to expansions.txt will go live/production when the next version is released (v2.2.4 ?)

**Comment by gregdeane** [comment]
I don't think v2.2.3 is live. Search "Nashville Plays Music" on the following files:

https://github.com/npm/npm-expansions/blob/v2.2.3/expansions.txt (search term found)
https://www.npmjs.com/static/js/index.min.6833b586.js (search term not found)

Again, might be a caching issue or a mistake on my part.

**Comment by jbruni** [comment]
Hmmm... indeed.

Look what I've found: https://github.com/npm/newww/commit/19f1feb631092afd0abe96d2e9ef41334384ac2e

**Comment by jonathanmarvens** [comment]
Just merged npm/newww#1703, so I'm closing this. Thanks, y'all :smile:.

**Comment by gregdeane** [comment]
@jonathanmarvens thanks!
